// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {appupdate} from '../models';
import {release} from '../models';
import {backup} from '../models';
import {config} from '../models';
import {browser} from '../models';
import {backend} from '../models';
import {logger} from '../models';
import {workspace} from '../models';
import {authsession} from '../models';
import {launchcode} from '../models';

export function ApplyDesktopAppUpdate():Promise<appupdate.State>;

export function ApplyDesktopReleaseUpdate():Promise<release.UpdateState>;

export function BackupExportPackage():Promise<Record<string, any>>;

export function BackupGetManifestTemplate():Promise<backup.Manifest>;

export function BackupGetScopeDefinition():Promise<backup.Scope>;

export function BackupImportPackage(arg1:boolean):Promise<Record<string, any>>;

export function BackupInitializeSystem():Promise<Record<string, any>>;

export function BookmarkList():Promise<Array<config.BrowserBookmark>>;

export function BookmarkReset():Promise<void>;

export function BookmarkSave(arg1:Array<config.BrowserBookmark>):Promise<void>;

export function BootstrapDesktopAuthRuntime():Promise<void>;

export function BrowserClearCookies(arg1:string):Promise<void>;

export function BrowserCoreDelete(arg1:string):Promise<void>;

export function BrowserCoreDownload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function BrowserCoreExtendedInfo():Promise<Array<browser.CoreExtendedInfo>>;

export function BrowserCoreList():Promise<Array<config.BrowserCore>>;

export function BrowserCoreSave(arg1:browser.CoreInput):Promise<void>;

export function BrowserCoreScan():Promise<Array<config.BrowserCore>>;

export function BrowserCoreSetDefault(arg1:string):Promise<void>;

export function BrowserCoreValidate(arg1:string):Promise<browser.CoreValidateResult>;

export function BrowserExportCookies(arg1:string):Promise<string>;

export function BrowserGetAllTags():Promise<Array<string>>;

export function BrowserGetCookies(arg1:string):Promise<Array<backend.CookieInfo>>;

export function BrowserInstanceGetTabs(arg1:string):Promise<Array<browser.Tab>>;

export function BrowserInstanceOpenUrl(arg1:string,arg2:string):Promise<boolean>;

export function BrowserInstanceRestart(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStart(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStartByCode(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStartWithParams(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:boolean):Promise<browser.Profile>;

export function BrowserInstanceStatus(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStop(arg1:string):Promise<browser.Profile>;

export function BrowserProfileBatchRemoveTags(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function BrowserProfileBatchSetTags(arg1:Array<string>,arg2:Array<string>,arg3:boolean):Promise<void>;

export function BrowserProfileCopy(arg1:string,arg2:string):Promise<browser.Profile>;

export function BrowserProfileCreate(arg1:browser.ProfileInput):Promise<browser.Profile>;

export function BrowserProfileDelete(arg1:string):Promise<void>;

export function BrowserProfileGetCode(arg1:string):Promise<string>;

export function BrowserProfileList():Promise<Array<browser.Profile>>;

export function BrowserProfileListByTag(arg1:string):Promise<Array<browser.Profile>>;

export function BrowserProfileRegenerateCode(arg1:string):Promise<string>;

export function BrowserProfileSetCode(arg1:string,arg2:string):Promise<string>;

export function BrowserProfileSetKeywords(arg1:string,arg2:Array<string>):Promise<browser.Profile>;

export function BrowserProfileUpdate(arg1:string,arg2:browser.ProfileInput):Promise<browser.Profile>;

export function BrowserProxyBatchCheckIPHealth(arg1:Array<string>,arg2:number):Promise<Array<backend.ProxyIPHealthResult>>;

export function BrowserProxyBatchTestSpeed(arg1:Array<string>,arg2:number):Promise<Array<backend.ProxyTestResult>>;

export function BrowserProxyCheckIPHealth(arg1:string):Promise<backend.ProxyIPHealthResult>;

export function BrowserProxyFetchClashByURL(arg1:string):Promise<Record<string, any>>;

export function BrowserProxyList():Promise<Array<config.BrowserProxy>>;

export function BrowserProxyListByGroup(arg1:string):Promise<Array<config.BrowserProxy>>;

export function BrowserProxyListGroups():Promise<Array<string>>;

export function BrowserProxyTestSpeed(arg1:string):Promise<backend.ProxyTestResult>;

export function BrowserRenameTag(arg1:string,arg2:string):Promise<void>;

export function BrowserSnapshotCreate(arg1:string,arg2:string):Promise<backend.SnapshotInfo>;

export function BrowserSnapshotDelete(arg1:string,arg2:string):Promise<void>;

export function BrowserSnapshotList(arg1:string):Promise<Array<backend.SnapshotInfo>>;

export function BrowserSnapshotRestore(arg1:string,arg2:string):Promise<void>;

export function CheckDesktopAppUpdate():Promise<appupdate.State>;

export function CheckDesktopReleaseUpdate():Promise<release.UpdateState>;

export function ClearAppLogs():Promise<void>;

export function ClearDesktopAppUpdateFailure():Promise<void>;

export function ClearDesktopAuthSession():Promise<void>;

export function ClearProfileSession(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function CreateGroup(arg1:browser.GroupInput):Promise<browser.Group>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DesktopAuthStrongCleanup(arg1:string):Promise<void>;

export function DownloadDesktopAppUpdate():Promise<appupdate.State>;

export function ExportDesktopEnvironmentDiagnostics():Promise<string>;

export function FetchDesktopAuthProfile(arg1:string):Promise<backend.DesktopAuthProfile>;

export function FetchDesktopSharedLoginBindSession(arg1:string,arg2:string):Promise<backend.DesktopSharedLoginBindSession>;

export function FetchRemoteAuthorProfile(arg1:string,arg2:number):Promise<Record<string, any>>;

export function ForceQuit():Promise<void>;

export function GenerateCDKeys(arg1:number):Promise<Array<string>>;

export function GetAppConfig():Promise<Record<string, any>>;

export function GetAppLogs():Promise<Array<logger.MemoryLogEntry>>;

export function GetBrowserSettings():Promise<browser.Settings>;

export function GetDashboardStats():Promise<Record<string, any>>;

export function GetDesktopAppUpdateState():Promise<appupdate.State>;

export function GetDesktopEnvironmentStatus():Promise<release.CheckResult>;

export function GetInterceptor():Promise<logger.MethodInterceptor>;

export function GetLaunchServerInfo():Promise<Record<string, any>>;

export function GetLicenseStatus():Promise<backend.LicenseStatus>;

export function GetLogLevel():Promise<string>;

export function GetMemoryStats():Promise<Record<string, any>>;

export function GetRunningInstances():Promise<Array<browser.Profile>>;

export function InjectManagedSessionBundle(arg1:string,arg2:workspace.SessionBundle):Promise<void>;

export function ListGroups():Promise<Array<browser.GroupWithCount>>;

export function LoadDesktopAuthSession():Promise<authsession.Session>;

export function LoginDesktopUser(arg1:string,arg2:string):Promise<string>;

export function MoveInstancesToGroup(arg1:Array<string>,arg2:string):Promise<void>;

export function OpenCorePath(arg1:string):Promise<void>;

export function OpenUserDataDir(arg1:string):Promise<void>;

export function QuitAppOnly():Promise<void>;

export function ReclaimManagedProfile(arg1:string):Promise<void>;

export function RedeemCDKey(arg1:string):Promise<void>;

export function RedeemGithubStar():Promise<void>;

export function ReloadConfig():Promise<void>;

export function RepairDesktopEnvironment():Promise<release.CheckResult>;

export function SaveBrowserProxies(arg1:Array<config.BrowserProxy>):Promise<void>;

export function SaveBrowserSettings(arg1:browser.Settings):Promise<void>;

export function SaveDesktopAuthSession(arg1:string,arg2:boolean):Promise<void>;

export function SetLogLevel(arg1:string):Promise<void>;

export function StartDesktopSharedLoginBind(arg1:string,arg2:string):Promise<backend.DesktopSharedLoginActionResult>;

export function StartDesktopSharedLoginValidate(arg1:string,arg2:string):Promise<backend.DesktopSharedLoginActionResult>;

export function StartInstance(arg1:string):Promise<browser.Profile>;

export function StartInstanceWithParams(arg1:string,arg2:launchcode.LaunchRequestParams):Promise<browser.Profile>;

export function StopInstance(arg1:string):Promise<boolean>;

export function TestProxyConnectivity(arg1:string,arg2:string):Promise<backend.ProxyTestResult>;

export function TestProxyRealConnectivity(arg1:string):Promise<backend.ProxyTestResult>;

export function TriggerGC():Promise<void>;

export function UpdateGroup(arg1:string,arg2:browser.GroupInput):Promise<browser.Group>;

export function UpsertManagedProfile(arg1:launchcode.ManagedProfileUpsertInput):Promise<launchcode.ManagedProfileUpsertResult>;

export function ValidateProxyConfig(arg1:string,arg2:string):Promise<backend.ProxyValidationResult>;

export function WorkspaceAuthorizedShops():Promise<Array<workspace.ShopInstanceProjection>>;

export function WorkspaceOpenShop(arg1:string):Promise<workspace.OpenShopResult>;

export function WorkspaceRunEvents(arg1:string,arg2:number):Promise<workspace.RunEventsPayload>;

export function WorkspaceRunEvidence(arg1:workspace.RunQuery):Promise<workspace.RunEvidenceIndex>;

export function WorkspaceRuns(arg1:workspace.RunQuery):Promise<workspace.RunsPayload>;

export function WorkspaceShopProfile(arg1:string):Promise<workspace.ShopProfileRecord>;

export function WorkspaceShopProfiles():Promise<Array<workspace.ShopProfileRecord>>;

export function WorkspaceSummary():Promise<workspace.WorkspaceSummary>;
