import type { RunRecord } from '../runEvidence/types'
import type { ShopProfile } from '../shops/types'
import type { WorkspaceAuthorizedShop, WorkspaceSummary } from './types'

export function useDevWorkspaceFallback(): boolean {
  return Boolean((import.meta as any).env?.DEV) && !(window as any)?.go?.main?.App
}

export const devWorkspaceSummary: WorkspaceSummary = {
  status: 'ready',
  agentStatus: 'running',
  sessionReady: true,
  serverReachable: true,
  antRuntimeReachable: true,
  activeRunCount: 1,
  deviceId: 'DEV-MAC',
  deviceStatus: 'ready',
}

export const devAuthorizedShops: WorkspaceAuthorizedShop[] = [
  {
    shopId: 'shop-ready',
    shopName: '义乌百货样板店',
    platformCode: '1688',
    profileId: 'profile-ready',
    instanceId: 'instance-ready',
    sharedLoginStatus: 'ready',
    sharedLoginStatusLabel: '可直接打开',
    instanceRunning: true,
    profileExists: true,
    reclaimPending: false,
    coreReady: true,
  },
  {
    shopId: 'shop-manual',
    shopName: '深圳数码配件店',
    platformCode: '1688',
    profileId: 'profile-manual',
    instanceId: '',
    sharedLoginStatus: 'awaiting_verification',
    sharedLoginStatusLabel: '待人工验证',
    instanceRunning: false,
    profileExists: true,
    reclaimPending: false,
    coreReady: true,
  },
  {
    shopId: 'shop-credential',
    shopName: '广州家居源头厂',
    platformCode: '1688',
    profileId: 'profile-credential',
    instanceId: '',
    sharedLoginStatus: 'expired',
    sharedLoginStatusLabel: '凭据待处理',
    instanceRunning: false,
    profileExists: true,
    reclaimPending: false,
    coreReady: true,
  },
]

export const devShopProfiles: ShopProfile[] = [
  {
    shopId: 'shop-ready',
    shopName: '义乌百货样板店',
    platformCode: '1688',
    asmStatus: 'connected',
    authorizationStatus: 'valid',
    ownerName: '运营一组',
    mainCategory: '日用百货',
    dataCompleteness: 'complete',
    lastSyncedAt: '2026-05-23T09:10:00+08:00',
    source: 'asm-dev',
  },
  {
    shopId: 'shop-manual',
    shopName: '深圳数码配件店',
    platformCode: '1688',
    asmStatus: 'connected',
    authorizationStatus: 'manual_required',
    ownerName: '运营二组',
    mainCategory: '数码配件',
    dataCompleteness: 'partial',
    lastSyncedAt: '2026-05-23T09:05:00+08:00',
    source: 'asm-dev',
  },
  {
    shopId: 'shop-credential',
    shopName: '广州家居源头厂',
    platformCode: '1688',
    asmStatus: 'error',
    authorizationStatus: 'expired',
    ownerName: '运营三组',
    mainCategory: '家居收纳',
    dataCompleteness: 'partial',
    lastSyncedAt: '2026-05-22T18:30:00+08:00',
    source: 'asm-dev',
  },
]

export const devWorkspaceRuns: RunRecord[] = [
  {
    runId: 'run-open-ready',
    taskId: 'task-open-ready',
    shopId: 'shop-ready',
    taskType: 'open',
    status: 'succeeded',
    statusLabel: '打开成功',
    startedAt: '2026-05-23T09:20:00+08:00',
    finishedAt: '2026-05-23T09:20:18+08:00',
    profileId: 'profile-ready',
    runtime: {
      pid: 61888,
      debugPort: 49210,
      currentUrl: 'https://work.1688.com/',
      pageTitle: '1688 商家工作台',
      targetUrl: 'https://work.1688.com/',
    },
    bindSessionId: '',
    manualActionRequired: false,
    challengeType: '',
    failureCode: '',
    failureMessage: '',
  },
  {
    runId: 'run-validate-manual',
    taskId: 'task-validate-manual',
    shopId: 'shop-manual',
    taskType: 'validate',
    status: 'awaiting_verification',
    statusLabel: '等待人工验证',
    startedAt: '2026-05-23T09:12:00+08:00',
    finishedAt: '',
    profileId: 'profile-manual',
    runtime: null,
    bindSessionId: 'bind-manual',
    manualActionRequired: true,
    challengeType: 'sms',
    failureCode: '',
    failureMessage: '',
  },
  {
    runId: 'run-bind-credential',
    taskId: 'task-bind-credential',
    shopId: 'shop-credential',
    taskType: 'bind',
    status: 'failed',
    statusLabel: '凭据更新失败',
    startedAt: '2026-05-22T18:35:00+08:00',
    finishedAt: '2026-05-22T18:35:21+08:00',
    profileId: 'profile-credential',
    runtime: null,
    bindSessionId: 'bind-credential',
    manualActionRequired: false,
    challengeType: '',
    failureCode: 'AUTH_EXPIRED',
    failureMessage: 'ASM 授权已失效，需要重新绑定登录态',
  },
]
