import type { RunRecord } from '../runEvidence/types'
import type { ShopProfile } from '../shops/types'
import type { WorkspaceAuthorizedShop, WorkspaceSummary } from './types'

const devShopProfileExtraFields = {
  shopStatusCode: 1,
  shopStatus: '正常',
  legalRepName: '',
  businessLicense: '',
  unifiedSocialCode: '',
  registeredAddress: '',
  categoryIds: [] as string[],
  categoryNames: [] as string[],
  brandIds: [] as string[],
  advancedMember: 0,
  trustPassExpireAt: '',
  jstShopCount: 0,
  jstShopSummary: '',
  mabangShopCount: 0,
  mabangShopSummary: '',
  erpShopCount: 0,
  erpShopSummary: '',
  abnormalCount: 0,
  abnormalSummary: '',
  tableSource: 'dev_mock',
  isPush: 0,
  sourceCreatedAt: '',
  sourceUpdatedAt: '',
}

export function useDevWorkspaceFallback(): boolean {
  return (
    Boolean((import.meta as any).env?.DEV)
    && String((import.meta as any).env?.VITE_ENABLE_DEV_WORKSPACE_FALLBACK || '').toLowerCase() === 'true'
    && !(window as any)?.go?.main?.App
  )
}

export const devWorkspaceSummary: WorkspaceSummary = {
  status: 'ready',
  agentStatus: 'running',
  sessionReady: true,
  serverReachable: true,
  antRuntimeReachable: true,
  activeRunCount: 1,
  deviceId: 'DEV-MAC',
  deviceStatus: 'ready',
}

export const devAuthorizedShops: WorkspaceAuthorizedShop[] = [
  {
    shopId: 'shop-ready',
    shopName: '义乌百货样板店',
    platformCode: '1688',
    profileId: 'profile-ready',
    instanceId: 'instance-ready',
    sharedLoginStatus: 'ready',
    sharedLoginStatusLabel: '可直接打开',
    instanceRunning: true,
    profileExists: true,
    reclaimPending: false,
    coreReady: true,
    lastOpenedAt: '',
    lastOpenFailureCode: '',
    lastOpenFailureMessage: '',
    lastOpenFailedAt: '',
  },
  {
    shopId: 'shop-manual',
    shopName: '深圳数码配件店',
    platformCode: '1688',
    profileId: 'profile-manual',
    instanceId: '',
    sharedLoginStatus: 'awaiting_verification',
    sharedLoginStatusLabel: '待人工验证',
    instanceRunning: false,
    profileExists: true,
    reclaimPending: false,
    coreReady: true,
    lastOpenedAt: '',
    lastOpenFailureCode: '',
    lastOpenFailureMessage: '',
    lastOpenFailedAt: '',
  },
  {
    shopId: 'shop-credential',
    shopName: '广州家居源头厂',
    platformCode: '1688',
    profileId: 'profile-credential',
    instanceId: '',
    sharedLoginStatus: 'expired',
    sharedLoginStatusLabel: '凭据待处理',
    instanceRunning: false,
    profileExists: true,
    reclaimPending: false,
    coreReady: true,
    lastOpenedAt: '',
    lastOpenFailureCode: '',
    lastOpenFailureMessage: '',
    lastOpenFailedAt: '',
  },
]

export const devShopProfiles: ShopProfile[] = [
  {
    ...devShopProfileExtraFields,
    shopId: 'shop-ready',
    shopName: '义乌百货样板店',
    asmShopId: 'dev-1001',
    shopCode: 'dev-shop-ready',
    shopAlias: '义乌百货样板店',
    fullShopName: '开发模拟-义乌百货样板店',
    platformCode: '1688',
    platformName: '1688',
    platformSubtype: 'dev',
    asmStatus: 'connected',
    authorizationStatus: 'valid',
    authorizationStatusLabel: '已授权',
    ownerName: '运营一组',
    operatorName: '开发运营一组',
    operatorUsername: 'dev_operator_ready',
    businessManagerName: '开发业务一组',
    businessManagerUsername: 'dev_manager_ready',
    department: '开发销售部',
    subCompanyName: '开发分公司',
    shopUrl: '',
    shopEmail: '',
    shopPhone: '',
    brandName: '开发品牌',
    advancedMemberName: '',
    mainCategory: '日用百货',
    dataCompleteness: 'complete',
    lastSyncedAt: '2026-05-23T09:10:00+08:00',
    source: 'dev_mock',
  },
  {
    ...devShopProfileExtraFields,
    shopId: 'shop-manual',
    shopName: '深圳数码配件店',
    asmShopId: 'dev-1002',
    shopCode: 'dev-shop-manual',
    shopAlias: '深圳数码配件店',
    fullShopName: '开发模拟-深圳数码配件店',
    platformCode: '1688',
    platformName: '1688',
    platformSubtype: 'dev',
    asmStatus: 'connected',
    authorizationStatus: 'manual_required',
    authorizationStatusLabel: '需要人工验证',
    ownerName: '运营二组',
    operatorName: '开发运营二组',
    operatorUsername: 'dev_operator_manual',
    businessManagerName: '开发业务二组',
    businessManagerUsername: 'dev_manager_manual',
    department: '开发销售部',
    subCompanyName: '开发分公司',
    shopUrl: '',
    shopEmail: '',
    shopPhone: '',
    brandName: '开发品牌',
    advancedMemberName: '',
    mainCategory: '数码配件',
    dataCompleteness: 'partial',
    lastSyncedAt: '2026-05-23T09:05:00+08:00',
    source: 'dev_mock',
  },
  {
    ...devShopProfileExtraFields,
    shopId: 'shop-credential',
    shopName: '广州家居源头厂',
    asmShopId: 'dev-1003',
    shopCode: 'dev-shop-credential',
    shopAlias: '广州家居源头厂',
    fullShopName: '开发模拟-广州家居源头厂',
    platformCode: '1688',
    platformName: '1688',
    platformSubtype: 'dev',
    asmStatus: 'error',
    authorizationStatus: 'expired',
    authorizationStatusLabel: '授权过期',
    ownerName: '运营三组',
    operatorName: '开发运营三组',
    operatorUsername: 'dev_operator_credential',
    businessManagerName: '开发业务三组',
    businessManagerUsername: 'dev_manager_credential',
    department: '开发销售部',
    subCompanyName: '开发分公司',
    shopUrl: '',
    shopEmail: '',
    shopPhone: '',
    brandName: '开发品牌',
    advancedMemberName: '',
    mainCategory: '家居收纳',
    dataCompleteness: 'partial',
    lastSyncedAt: '2026-05-22T18:30:00+08:00',
    source: 'dev_mock',
  },
]

export const devWorkspaceRuns: RunRecord[] = [
  {
    runId: 'run-open-ready',
    taskId: 'task-open-ready',
    shopId: 'shop-ready',
    taskType: 'open',
    status: 'succeeded',
    statusLabel: '打开成功',
    startedAt: '2026-05-23T09:20:00+08:00',
    finishedAt: '2026-05-23T09:20:18+08:00',
    profileId: 'profile-ready',
    runtime: {
      pid: 61888,
      debugPort: 49210,
      currentUrl: 'https://work.1688.com/',
      pageTitle: '1688 商家工作台',
      targetUrl: 'https://work.1688.com/',
    },
    bindSessionId: '',
    manualActionRequired: false,
    challengeType: '',
    failureCode: '',
    failureMessage: '',
  },
  {
    runId: 'run-validate-manual',
    taskId: 'task-validate-manual',
    shopId: 'shop-manual',
    taskType: 'validate',
    status: 'awaiting_verification',
    statusLabel: '等待人工验证',
    startedAt: '2026-05-23T09:12:00+08:00',
    finishedAt: '',
    profileId: 'profile-manual',
    runtime: null,
    bindSessionId: 'bind-manual',
    manualActionRequired: true,
    challengeType: 'sms',
    failureCode: '',
    failureMessage: '',
  },
  {
    runId: 'run-bind-credential',
    taskId: 'task-bind-credential',
    shopId: 'shop-credential',
    taskType: 'bind',
    status: 'failed',
    statusLabel: '凭据更新失败',
    startedAt: '2026-05-22T18:35:00+08:00',
    finishedAt: '2026-05-22T18:35:21+08:00',
    profileId: 'profile-credential',
    runtime: null,
    bindSessionId: 'bind-credential',
    manualActionRequired: false,
    challengeType: '',
    failureCode: 'AUTH_EXPIRED',
    failureMessage: 'ASM 授权已失效，需要重新绑定登录态',
  },
]
